### ISSUE TITLE
Error: cudaCheckError() failed : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by guillaumejaume** [rowanz/neural-motifs#14]
Hi, 
When running the script `eval_rels.py` to test the baseline model, I get the error `cudaCheckError() failed : no kernel image is available for execution on the device`, in `eval_rels.py/val_batch(...)` line `det_res = detector[b]`. 

I'm running on a P100 GPU, with python 3.5, CUDA 9.2, PyTorch 0.3.1. I set in `lib/lstm/highway_lstm_cuda/make.sh`  the `CUDA_MODELS` to 60. In this way, the highway LSTM is compiled with `/usr/local/cuda/bin/nvcc -c -o highway_lstm_kernel.cu.o highway_lstm_kernel.cu.o --compiler-options -fPIC -gencode arch=compute_60,code=sm_60`.  The compilation of the CPython lib seems to work fine. 

Do you have an idea what could be the problem? Thanks in advance!

**Comment by guillaumejaume** [comment]
Solved by changing hardcoded CUDA param `arch=compute_61,code=sm_61` to `arch=compute_60,code=sm_60` in `lib/fpn/nms/src/cuda/Makefile` and `lib/fpn/roi_align/src/cuda/Makefile`.

**Comment by YiwuZhong** [comment]
Thanks for your information. But I use CUDA 9.2 and P100, I got the error `_highway_lstm_layer.so: undefined symbol: __cudaPopCallConfiguration`. Have you ever met the same problem?
