### ISSUE TITLE
pytorch > 1?

### ISSUE THREAD

**Issue by sharifza** [rowanz/neural-motifs#74]
is there any pytorch > 1 fork of this work? There is no way to run it in this shape with newer GPUs such as RTX as they do not support cuda versions less than 10 while pytorch versions < 1 don't support cuda10 !

**Comment by zaynmi** [comment]
I have the same problem with 2080Ti, throwing out error 
```
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /home/tang/pytorch/torch/lib/THC/generic/THCTensorMathPairwise.cu:21
```
Looking for solution

**Comment by sharifza** [comment]
Yes, exactly the same error.

**Comment by truetone2022** [comment]
Anyone solved this problem? I meet it too.

**Comment by TP0609** [comment]
> is there any pytorch > 1 fork of this work? There is no way to run it in this shape with newer GPUs such as RTX as they do not support cuda versions less than 10 while pytorch versions < 1 don't support cuda10 !

Hello  !
Is your problem solved? I am using RTX2070, not supporting version less than cuda10.0, but cuda10.0 needs to use pytorch>1.0, can this program be run with pytorch>1.0?  !
Is your problem solved? I am using RTX2070, not supporting version less than cuda10.0, but cuda10.0 needs to use pytorch>1.0, can this program be run with pytorch>1.0?

**Comment by GreenTeaHua** [comment]
torchvision.ops.nms(boxes, scores, iou_threshold)
    Performs non-maximum suppression (NMS) on the boxes according
    to their intersection-over-union (IoU).

    NMS iteratively removes lower scoring boxes which have an
    IoU greater than iou_threshold with another (higher scoring)
    box.

    Parameters
    ----------
    boxes : Tensor[N, 4])  bounding boxes坐标. 格式：(x1, y1, x2, y2)
        boxes to perform NMS on. They
        are expected to be in (x1, y1, x2, y2) format
    scores : Tensor[N]   bounding boxes得分
        scores for each one of the boxes
    iou_threshold : float IoU过滤阈值
        discards all overlapping
        boxes with IoU < iou_threshold

    Returns
    -------
    keep : Tensor
        int64 tensor with the indices
        of the elements that have been kept
        by NMS, sorted in decreasing order of scores
        NMS过滤后的bouding boxes索引（降序排列）
    """

**Comment by progvasu** [comment]
> > is there any pytorch > 1 fork of this work? There is no way to run it in this shape with newer GPUs such as RTX as they do not support cuda versions less than 10 while pytorch versions < 1 don't support cuda10 !
> 
> Hello !
> Is your problem solved? I am using RTX2070, not supporting version less than cuda10.0, but cuda10.0 needs to use pytorch>1.0, can this program be run with pytorch>1.0? !
> Is your problem solved? I am using RTX2070, not supporting version less than cuda10.0, but cuda10.0 needs to use pytorch>1.0, can this program be run with pytorch>1.0?

Hey,

Where you able to figure this out? Thanks!

**Comment by Spichon** [comment]
Hi guys,
So i did figure out how to go through the "no kernel image is available for execution" issue if you are running the code with a RTX2080. 
You have to edit the file /lib/lstm/highway_lstm/make.sh with the following value : CUDA_MODELS=(75).

Nevertheless, pytorch 0.4.1 can't deal with cuda10. You can refer to the following zoo model : https://download.pytorch.org/whl/cu100/torch_stable.html

The solution would be to get this code working with torch > 1.0.

**Comment by TP0609** [comment]
charge 2070 to  GTX1080TI (11G),  The  problem is solved!  because the  2070 insufficient memory









At 2020-02-24 23:42:07, "Simon Pichon" <notifications@github.com> wrote:

Hi guys,
So i did figure out how to go through the "no kernel image is available for execution" issue if you are running the code with a RTX2080.
You have to edit the file /lib/lstm/highway_lstm/make.sh with the following value : CUDA_MODELS=(75).

Nevertheless, pytorch 0.4.1 can't deal with cuda10. You can refer to the following zoo model : https://download.pytorch.org/whl/cu100/torch_stable.html

The solution would be to get this code working with torch > 1.0.
